package com.webattalia.game;

public enum Action {
	SUMMON_HERO,
	UPGRADE_TO_CITY_TWO,
	UPGRADE_TO_CITY_THREE,
	UPGRADE_TO_CITY_FOUR,
	MOVE_HERO_ONE,
	MOVE_HERO_THREE,
	START_BATTLE,
	ERECT_TENT,
	RETREAT_WITH_SUPPLY,
	RETREAT_WITH_HORSE,
	ACTIVATE_HERO_ABILITY_TWO,
	ACTIVATE_HERO_ABILITY_THREE,
	BRIBE_UNBOUND_BUFF,
	HIRE_UNBOUND_BUFF
}
